

# brainboost_data_source_requests_package
# Configurable Parameters

storage_proxy_pool_database_path='/brainboost/brainboost_data/data_storage/storage_requests_package/storage_requests_proxy_database/proxies_db.json'
storage_user_agent_pool_database_path='/brainboost/brainboost_data/data_storage/storage_user_agents_database/data_source_user_agents.txt'

storage_local_mercadolibre_colombia_visited_links = '/brainboost/brainboost_data/data_storage/storage_local/storage_local_mercadolibre_colombia/mercadolibre_colombia_visited_links.json'